/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestView: typeof import('./../../../libs/components/src/test/TestView.vue')['default']
    TestVueUse: typeof import('./components/test/TestVueUse.vue')['default']
  }
}
